services:
  #PHP
  php:
    image: php:8.3.0-fpm
    volumes:
      - php_data:/var/www/html
    container_name: melanieehrmann_php

  #Database
  database:
    image: mariadb:11.2.3
    volumes:
      - db-data:/var/lib/mysq
    env_file:
      - .env.local
    ports:
      - 3307:3306
    container_name: melanieehrmann_database

volumes:
  php_data:
  db-data:
