services:
  #Database
  database:
    ports:
      - "5432:5432"

  #Symfony Mailer
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    container_name: melanieehrmann_mailer